//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesajlar
    {
        public int mesajId { get; set; }
        public int mesajSohbetId { get; set; }
        public int mesajUserId { get; set; }
        public string icerik { get; set; }
        public System.DateTime gonderimTarihi { get; set; }
    
        public virtual Sohbetler Sohbetler { get; set; }
        public virtual Users Users { get; set; }
    }
}
